import { StyleSheet } from "@react-pdf/renderer"

export const pdfColors = {
  navy: "#061E68",
  gold: "#D6993A",
  goldLight: "#E4C07C",
  ink: "#171717",
  muted: "#5F6368",
  line: "#E4E4E7",
  soft: "#F7F7F8",
  white: "#FFFFFF",
} as const

export const pdfStyles = StyleSheet.create({
  page: {
    backgroundColor: pdfColors.white,
    color: pdfColors.ink,
    fontFamily: "Helvetica",
    fontSize: 10,
    lineHeight: 1.5,
    paddingBottom: 48,
    paddingHorizontal: 38,
    paddingTop: 34,
  },
  header: {
    alignItems: "center",
    borderBottomColor: pdfColors.line,
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 22,
    paddingBottom: 12,
  },
  logo: { height: 44, objectFit: "contain", width: 78 },
  brandText: { color: pdfColors.navy, fontSize: 9, fontWeight: 700 },
  eyebrow: {
    color: pdfColors.gold,
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 0.8,
    marginBottom: 7,
    textTransform: "uppercase",
  },
  title: {
    color: pdfColors.navy,
    fontSize: 27,
    fontWeight: 700,
    lineHeight: 1.15,
    marginBottom: 8,
  },
  subtitle: { color: pdfColors.muted, fontSize: 12, marginBottom: 16 },
  hero: { height: 250, objectFit: "cover", width: "100%" },
  heroFrame: {
    borderColor: pdfColors.line,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 18,
    overflow: "hidden",
  },
  section: { marginBottom: 18 },
  sectionTitle: {
    color: pdfColors.navy,
    fontSize: 15,
    fontWeight: 700,
    marginBottom: 8,
  },
  body: { color: pdfColors.muted, fontSize: 10, lineHeight: 1.6 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: {
    backgroundColor: pdfColors.soft,
    borderColor: pdfColors.line,
    borderRadius: 10,
    borderWidth: 1,
    color: pdfColors.navy,
    fontSize: 8.5,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  gallery: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  galleryItem: {
    borderColor: pdfColors.line,
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
    width: "48.9%",
  },
  galleryImage: { height: 128, objectFit: "cover", width: "100%" },
  caption: { padding: 8 },
  captionTitle: { color: pdfColors.navy, fontSize: 9, fontWeight: 700 },
  captionText: { color: pdfColors.muted, fontSize: 7.5, marginTop: 3 },
  contact: {
    backgroundColor: pdfColors.soft,
    borderColor: pdfColors.goldLight,
    borderRadius: 10,
    borderWidth: 1,
    padding: 14,
  },
  link: { color: pdfColors.navy, fontSize: 9, marginTop: 6 },
  footer: {
    bottom: 18,
    color: pdfColors.muted,
    flexDirection: "row",
    fontSize: 7.5,
    justifyContent: "space-between",
    left: 38,
    position: "absolute",
    right: 38,
  },
})
